language: java
# jdk: oraclejdk9 -- using jdk-10-ea now

sudo: false
dist: trusty

# Specify which branches/tags that we do not want to be built: r5.0.0-M5
branches:
  except:
    - /^r\d.*$/

# Don't let Travis CI execute './gradlew assemble' by default
install:
# "dot source" the jdk installation script
  - . ./src/scripts/install-jdk.sh

script:
  - ./gradlew build --scan --stacktrace
